# Generated by Django 3.2.7 on 2021-09-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_updater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webnews',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webnews',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
